
//iife to generate dom grid to hold nodes generated by this.
const taskBody = (()=>{
    let content = document.getElementById("content");
    let body = document.getElementById("body");
        let taskBody = document.createElement("div");
        let header = document.createElement("header");
            taskBody.setAttribute("id", "taskBody");
            header.setAttribute("class", "header");

        content.appendChild(taskBody);
        body.appendChild(header);
    



    return {
        taskBody,
        content,
    }
})();

const background = (() => {


    let bgModal= document.createElement("div");
            bgModal.setAttribute("name", "title");
            bgModal.setAttribute("class", "bgModal");

    let modal = document.createElement("div");
            modal.setAttribute("class", "modal");


    let close = document.createElement("div");
            close.setAttribute("class","close");
            close.textContent = "+";

    let addTask = document.createElement("div");
            addTask.setAttribute("class","addTask");
            addTask.setAttribute("id","addTask");
            addTask.textContent = "+";


        taskBody.content.appendChild(bgModal);
        bgModal.appendChild(modal);
        modal.appendChild(close);
        taskBody.taskBody.appendChild(addTask);

        return{
            modal,
        }

})();

// create a dom for the get of title. 
// Generates dom for title.
const taskForm = (() => {
    //Creates form.


    let form = document.createElement("div");
    
        // form.setAttribute("action", "submit.php");

        let title = document.createElement("input");
            title.setAttribute("name", "title");
            title.setAttribute("type", "text");
            title.setAttribute("id", "titleDom");
            title.setAttribute("class","input")

        let description = document.createElement("input");
            description.setAttribute("name", "desc");
            description.setAttribute("type", "text");
            description.setAttribute("id", "descDom");
            description.setAttribute("class","input")

        let submit = document.createElement("button");
            submit.setAttribute('id', "submit");
                
            form.appendChild(title);
            form.appendChild(description);
            form.appendChild(submit);
            background.modal.appendChild(form);

        

    
})();


// Creates a background for the task form modal.


// Generates dark background for when task related elements are selected.
const bgTask =(() => {


    let bgTask= document.createElement("div");
            bgTask.setAttribute("name", "title");
            bgTask.setAttribute("class", "bgTask");
            taskBody.content.appendChild(bgTask);

    // the modal where the task will sit on.
    let modalTask = document.createElement("div");
            modalTask.setAttribute("class", "modalTask");
            bgTask.appendChild(modalTask);
            
        return{
            bgTask,
            modalTask,
        }

})();

// Loads both of the dom elements.
const taskDomGen = (() => {
    taskForm();
    taskBody();
})

export { taskDomGen, bgTask }