
//iife to generate dom grid to hold nodes generated by this.
const taskBody = (()=>{
    let content = document.getElementById("content");
        let taskBody = document.createElement("div");
            taskBody.setAttribute("id", "taskBody");
        content.appendChild(taskBody);

    return {
        taskBody,
    }
})();

// Generates dom for title.
const taskForm = (() => {
    let title = document.createElement("div");
        let description = document.createElement("div");
            title.setAttribute("id", "titleDom");
            description.setAttribute("id", "descDom");
            taskBody.taskBody.appendChild(title);
        taskBody.taskBody.appendChild(description);
})();

const taskDomGen = (() => {
    taskForm();
    taskBody();
})

export { taskDomGen }